### ISSUE TITLE
Middlewares/Internals project

### ISSUE THREAD

**Issue by schnittstabil** [middlewares/internals#1]
I think it would be useful to have this project here. Create issues for everything which seems appropriate, so we may discuss them. Thus, this would be like a message board for internal organisation discussions.

If @oscarotero thinks that there is no need for this project, then I'll be fine as well.

**Comment by oscarotero** [comment]
My initial intention was using https://github.com/middlewares/psr15-middlewares for that purpose, but I think it's fine to move it here. 👍

**Comment by schnittstabil** [comment]
*Middlewares/Internals* would target the *Middlewares Organisation*, not PSR decisions …
