### ISSUE TITLE
New packages

### ISSUE THREAD

**Issue by schnittstabil** [middlewares/internals#2]
I want to create a new `middlewares/module-requests` project. Take a look at [sindresorhus/module-requests](https://github.com/sindresorhus/module-requests). It could act as a platform not only for new comers who need specific middlewares, but also for developers who search for new ideas.

I'm a bit shilly shally about the name:
* *middlewares/module-requests* or
* *middlewares/package-requests* or
* … or???

@eusonlito, @mindplay-dk, @oscarotero, @sbol-coolblue What do you think?

**Comment by oscarotero** [comment]
There's a project with random ideas here: https://github.com/middlewares/psr15-middlewares/projects/1 

I'm not sure about creating a package for this, a issue label should be enough. I prefer to have less organization/bureaucracy-packages and more code-packages

**Comment by schnittstabil** [comment]
I wasn't aware of https://github.com/middlewares/psr15-middlewares/projects/1 – nice, idea!

However, as far as I can see, it doesn't provide room for discussions. E.g. maybe there is already a project solving that issue, or creating a middleware wouldn't be the right thing etc.

Furthermore, I don't want it to be a *bureaucracy package*. If there is a valid need for a middleware, and even if organisation members agree about its usefulness, then that still does not mean the *middlewares organisation* MUST/SHOULD implement it.

Every OSS developer who is searching for new ideas may create its very first middleware package, just because he get inspired by those issues. It also doesn't mean that the developer must transfer it to the middleware organisation or similar.

Hence, it would be about *inspiration* and the naming is not appropriate, what about:
* *middlewares/module-ideas*
* *middlewares/package-ideas*

**Comment by oscarotero** [comment]
Yes, I know that is not the best tool to handle new ideas.

So, finally we'll have the following non-code repos:

* [psr15-middlewares](https://github.com/middlewares/psr15-middlewares) the main repo, with the index of all packages, an explanation about the project, how to collaborate, etc
* [internals](https://github.com/middlewares/internals/) for internal discussions
* [awesome-psr15](https://github.com/middlewares/awesome-psr15-middlewares) With links to not only our packages, but also external packages, articles, etc.
* [skeleton](https://github.com/middlewares/skeleton) A skeleton repository to create new packages
* And this new package for new ideas.

I vote for simply *middlewares/ideas* but if you prefer a more descriptive name, *package-ideas*

**Comment by schnittstabil** [comment]
:+1: we should not have too much of these. It would be unfortunate if we want to create repos someday like:
* *middlewares/enhancement-ideas*
* …

I think *middlewares/ideas* works fine.

**Comment by schnittstabil** [comment]
@oscarotero Did you hand-lettered the [MW logo](https://avatars1.githubusercontent.com/u/22275359?v=3&s=200) or did you used a font, and in case which one? – I want to create a _KEEP CALM AND GET IDEAS_-image for [middlewares/ideas](https://github.com/middlewares/ideas), hence may you mind to share the logo at a `middlewares/art` repository?

**Comment by oscarotero** [comment]
@schnittstabil thanks for create the repo. I should move the middleware ideas from https://github.com/middlewares/psr15-middlewares/projects/1 to middleware/ideas.
And about the logo, I'm going to upload the svg as soon I have the computer in which is stored, but not sure about `middlewares/art`, it would be another bureaucracy package. Maybe we can upload it to the main repo `middlewares/psr15-middlewares` and put a link in the readme.

**Comment by oscarotero** [comment]
Here's the logo.
https://github.com/middlewares/psr15-middlewares/tree/master/art

**Comment by schnittstabil** [comment]
Awesome! Btw, how do you convert svg to png? – Currently I use [`svg-to-png`](https://www.npmjs.com/package/svg-to-png), maybe you know a better alternative.

**Comment by oscarotero** [comment]
I've created and exported the logo using Adobe Illustrator :)
