### ISSUE TITLE
We need a team

### ISSUE THREAD

**Issue by schnittstabil** [middlewares/internals#3]
It's really cumbersome to write … @eusonlito, @mindplay-dk, @oscarotero, @sbol-coolblue … all the time. Moreover, this organisation may grow, and it would be impossible to address questions to the whole organisation.

Hence, I would suggest to create at least one team. E.g. `contributors`
And team members can we can ping the whole team, by `@middlewares/contributors`

Sorry guys, I see, I've created some noise here. And I don't want to bother you anymore, but I believe this would help the *middlewares organisation* to grow. Furthermore, if you don't want to be a contributors team member, you will get less messages…

**Comment by oscarotero** [comment]
Good idea. I've created the team and added all people in this organization. If anyone don't want to be a member of the team, feel free to leave it.
